# Generated by Django 4.0.4 on 2022-06-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
