# Generated by Django 4.0.4 on 2022-11-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_profile_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
    ]
